# Generated by Django 2.0.7 on 2018-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('accountName', models.CharField(max_length=200)),
                ('twitterId', models.CharField(max_length=200)),
                ('screenName', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('profileImage', models.CharField(blank=True, max_length=200, null=True)),
                ('bannerUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('statusesCount', models.IntegerField(blank=True, null=True)),
                ('friendsCount', models.IntegerField(blank=True, null=True)),
                ('accountTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('tweetsId', models.AutoField(primary_key=True, serialize=False)),
                ('accountId', models.IntegerField()),
                ('tweetsText', models.TextField()),
                ('tweetsUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('twitterId', models.CharField(max_length=200)),
                ('imageUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('videoUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('retweetCount', models.IntegerField(blank=True, null=True)),
                ('tweetFavCount', models.IntegerField(blank=True, null=True)),
                ('tweetTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
