# Generated by Django 2.0.7 on 2018-07-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inforShow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='tweets',
            table='tweets',
        ),
    ]
