# Generated by Django 2.0.7 on 2018-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforShow', '0002_auto_20180711_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favoritesCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='followersCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
